export type ThemeId = "habit" | "food";

export type ThemeConfig = {
  id: ThemeId;
  label: string;
  emoji: string;
  headline: string;
  subtitle: string;
  starter: string;
  choices: string[];
  imagePrompt: string;
  badgePool: string[];
};

export const themes: Record<ThemeId, ThemeConfig> = {
  habit: {
    id: "habit",
    label: "幼习宝",
    emoji: "✨",
    headline: "一日生活提醒智能体，练习喝水、洗手、如厕、整理、排队和文明进餐。",
    subtitle: "适合晨间、餐前餐后、如厕整理、排队过渡和班级常规跟进。",
    starter:
      "你好呀，我是幼习宝小星。今天我们一起练一日生活小本领：洗手、喝水、如厕、排队、整理和文明进餐。你想先听哪个 AI 小提醒？",
    choices: ["好习惯闯关", "习惯故事小剧场", "对老师说", "老师给我的任务"],
    imagePrompt:
      "绘本风，明亮温暖，幼儿园教室里，圆润可爱的习惯小星带着孩子洗手、排队、整理书本，奶油黄和海盐蓝配色，儿童插画，高细节，安全友好。",
    badgePool: ["洗手闪亮章", "喝水小勇士章", "排队小队长章", "文明进餐章"],
  },
  food: {
    id: "food",
    label: "闽食成长岛",
    emoji: "🦪",
    headline: "和海蛎小勇士逛泉州美食小岛，认识名字、食材和小故事。",
    subtitle: "适合餐前引导、食育故事和家园共育。",
    starter:
      "欢迎来到闽食成长岛，我是海蛎小勇士。今天可以看今日食谱、坐闽食小列车、去泉州美食摊位寻宝，再做美食观察与靠近一点点。",
    choices: [
      "今日食谱",
      "闽食小列车",
      "泉州美食摊位寻宝",
      "美食观察与靠近一点点",
      "泉州小厨房",
      "小小闽食播报员",
    ],
    imagePrompt:
      "儿童绘本风，泉州古城和海边美食小岛场景，海蛎小勇士带着孩子体验闽食小列车、泉州美食摊位寻宝、美食观察与靠近一点点和小小闽食播报员，画面中有海蛎煎、面线糊、润饼菜、石花膏、土笋冻、炸醋肉、崇武鱼卷、姜母鸭、烧肉粽、芋头饼、牛肉羹、洪濑鸡爪、四果汤和咸饭，明亮温暖，卡通可爱，安全友好。",
    badgePool: ["闽食小侦探", "食材发现章", "古城小导游", "亲近美食章"],
  },
};

export const lifeHabitKnowledge = [
  {
    key: "喝水",
    cue: "小水杯，双手拿，接半杯，慢慢喝。",
    steps: ["双手拿杯", "接半杯", "坐好慢慢喝", "放回水杯"],
    homeTask: "回家请孩子自己拿水杯，接半杯，坐好慢慢喝一口。",
  },
  {
    key: "洗手",
    cue: "挽袖子，打湿手，搓泡泡，冲干净，擦小手。",
    steps: ["挽袖子", "打湿手", "搓泡泡", "冲干净", "擦小手"],
    homeTask: "饭前请孩子说出洗手顺序，再完成一次洗手。",
  },
  {
    key: "如厕",
    cue: "轻轻进，便后冲，整理好，洗小手。",
    steps: ["轻轻进入", "便后冲水", "整理衣物", "洗小手"],
    homeTask: "回家提醒孩子如厕后冲水、整理衣物、再洗手。",
  },
  {
    key: "整理",
    cue: "玩具回家，书本摆齐，椅子归位。",
    steps: ["玩具回家", "书本摆齐", "椅子归位", "桌面清爽"],
    homeTask: "睡前请孩子把一本书或一个玩具送回原位。",
  },
  {
    key: "排队",
    cue: "不推挤，跟上前，静悄悄，排整齐。",
    steps: ["不推挤", "跟上前", "静悄悄", "排整齐"],
    homeTask: "外出等待时，请孩子练习排队、等待和跟上前面的人。",
  },
  {
    key: "进餐",
    cue: "手扶碗，脚放稳，安静嚼，不撒饭，愿意认识新食物。",
    steps: ["手扶碗", "脚放稳", "安静嚼", "不撒饭", "按需取餐"],
    homeTask: "晚餐时请孩子练一项：手扶碗、慢慢嚼或餐后整理。",
  },
];

export const habitSkillCards = [
  {
    title: "洗手小任务",
    icon: "🫧",
    hint: "饭前便后先洗手，挽袖子、打湿手、搓泡泡、冲干净、擦小手。",
    tone: "bg-cyan-100 text-cyan-900",
    taskName: "洗手小任务",
    gameKey: "washSteps",
    badgeName: "洗手闪亮章",
    command: "挽袖子，打湿手，搓泡泡，冲干净，擦小手。",
    rhyme: "小袖子，卷一卷，小泡泡，转圈圈，冲一冲，擦一擦，干净小手来吃饭。",
    question: "饭前第一步可以做什么？",
    actionLabel: "我会先洗手",
    knowledge: "洗手任务用于观察幼儿能否记住饭前便后的基本顺序。",
  },
  {
    title: "喝水小任务",
    icon: "🥤",
    hint: "口渴或活动后，坐好慢慢喝，不拿杯子跑。",
    tone: "bg-sky-100 text-sky-900",
    taskName: "喝水小任务",
    gameKey: "queue",
    badgeName: "喝水小勇士章",
    command: "小水杯，双手拿，接半杯，慢慢喝。",
    rhyme: "小水杯，手里拿，接半杯，不洒啦，慢慢喝，身体舒服啦。",
    question: "喝水时身体可以怎么做？",
    actionLabel: "我会慢慢喝",
    knowledge: "喝水任务关注幼儿是否能在活动后主动补水，并保持安全动作。",
  },
  {
    title: "如厕小任务",
    icon: "🚻",
    hint: "想上厕所先告诉老师，结束后整理衣物再洗手。",
    tone: "bg-teal-100 text-teal-900",
    taskName: "如厕小任务",
    gameKey: "queue",
    badgeName: "如厕小任务章",
    command: "轻轻进，便后冲，整理好，洗小手。",
    rhyme: "如厕轻轻走，便后冲一冲，小手洗干净，自己真能行。",
    question: "想上厕所时可以先做什么？",
    actionLabel: "我会告诉老师",
    knowledge: "如厕提醒帮助幼儿把表达需要、整理衣物和洗手连成稳定流程。",
  },
  {
    title: "排队小队长",
    icon: "🚩",
    hint: "一个跟着一个走，慢慢走，不推不挤。",
    tone: "bg-amber-100 text-amber-900",
    taskName: "排队小任务",
    gameKey: "queue",
    badgeName: "排队小队长章",
    command: "不推挤，跟上前，静悄悄，排整齐。",
    rhyme: "小队伍，一条线，静悄悄，不抢先。",
    question: "排队时可以怎么走？",
    actionLabel: "我会慢慢走",
    knowledge: "排队任务用于观察幼儿在过渡环节是否能等待、跟随和保持安全距离。",
  },
  {
    title: "整理小能手",
    icon: "🧺",
    hint: "玩具、图书、桌面物品都能慢慢归位。",
    tone: "bg-orange-100 text-orange-900",
    taskName: "整理小任务",
    gameKey: "queue",
    badgeName: "整理小能手",
    command: "玩具回家，书本摆齐，椅子归位。",
    rhyme: "小玩具，有个家，书本齐，椅子靠，教室笑哈哈。",
    question: "玩完以后可以怎么做？",
    actionLabel: "我送回家",
    knowledge: "整理任务能延伸到阅读区、建构区和餐后桌面，适合老师观察迁移能力。",
  },
  {
    title: "文明进餐操",
    icon: "🥣",
    hint: "扶好碗、坐稳、细嚼慢咽，练午餐前后能用的动作。",
    tone: "bg-amber-100 text-amber-900",
    taskName: "文明进餐小任务",
    gameKey: "mealManners",
    badgeName: "文明进餐章",
    command: "手扶碗，脚放稳，安静嚼，不撒饭。",
    rhyme: "小手扶碗边，小脚稳稳站，饭菜慢慢嚼，餐后整理好。",
    question: "吃饭时可以先做哪一个好动作？",
    actionLabel: "我会扶好碗",
    knowledge: "进餐习惯不是催孩子吃完，而是练坐稳、慢慢嚼、按需取和餐后整理。",
  },
  {
    title: "好习惯红绿牌",
    icon: "🟢",
    hint: "听一个行为，举绿牌或红牌，再说出正确做法。",
    tone: "bg-emerald-100 text-emerald-900",
    taskName: "红绿牌小游戏",
    gameKey: "habitTrafficLight",
    badgeName: "好习惯判断章",
    command: "听到好习惯举绿牌，看到需要调整的做法举红牌。",
    rhyme: "绿牌亮，好习惯；红牌停，换办法。",
    question: "饭前洗手应该举什么牌？",
    actionLabel: "我会举绿牌",
    knowledge: "红绿牌适合识别进餐、整理、阅读和情绪表达中的正确做法。",
  },
  {
    title: "习惯故事小剧场",
    icon: "📚",
    hint: "找一本小故事，听一听绘本，今天读完啦。",
    tone: "bg-violet-100 text-violet-900",
    taskName: "听绘本打卡",
    gameKey: "readingCheckin",
    badgeName: "故事小耳朵",
    command: "找一本小故事，听一听绘本，翻到最后一页再打卡。",
    rhyme: "小故事，轻轻听，一页一页慢慢翻。",
    question: "你最喜欢哪一页？",
    actionLabel: "今天读完啦",
    knowledge: "故事小剧场用于培养阅读习惯，重点观察幼儿是否愿意听绘本、翻页、表达喜欢的故事并完成阅读打卡。",
  },
];

export const readingCheckinTasks = [
  {
    title: "每日听故事",
    icon: "👂",
    prompt: "我听到了谁？",
    answerCards: ["小星", "小朋友", "会发光的小书"],
    praise: "你认真听到故事角色啦，故事小耳朵亮起来。",
  },
  {
    title: "亲子共读 5 分钟",
    icon: "👨‍👩‍👧",
    prompt: "我看到了什么？",
    answerCards: ["一页图画", "一个角色", "一个好习惯"],
    praise: "你会把看到的画面说出来，阅读小书虫真专注。",
  },
  {
    title: "图书归位",
    icon: "📚",
    prompt: "看完书放哪里？",
    answerCards: ["放回书架", "轻轻合上", "按标记归位"],
    praise: "图书回到自己的家，整理小能手也在发光。",
  },
  {
    title: "故事表达",
    icon: "💬",
    prompt: "我喜欢哪里？",
    answerCards: ["喜欢角色", "喜欢画面", "喜欢一个好办法"],
    praise: "你能说出喜欢的地方，故事表达完成啦。",
  },
];

export const foodBadgeCards = [
  {
    title: "闽食小寻宝",
    icon: "🧭",
    description: "去找一找家里、学校或街边看到的闽食。",
  },
  {
    title: "亲近美食章",
    icon: "🥢",
    description: "愿意认名字、找食材、靠近一点点，也算勇敢。",
  },
  {
    title: "家庭小主厨",
    icon: "👨‍🍳",
    description: "和家人一起做一份简单闽食，拍照留念。",
  },
  {
    title: "闽食宣传员",
    icon: "📣",
    description: "会介绍一种闽食名字和它的特别之处。",
  },
];

export const rewardStickerCards = [
  {
    title: "坐姿闪亮章",
    icon: "⭐",
    tone: "bg-amber-100 text-amber-900",
  },
  {
    title: "勇敢尝试章",
    icon: "🥄",
    tone: "bg-rose-100 text-rose-900",
  },
  {
    title: "阅读小书虫",
    icon: "🐛",
    tone: "bg-violet-100 text-violet-900",
  },
  {
    title: "故事小耳朵",
    icon: "👂",
    tone: "bg-sky-100 text-sky-900",
  },
  {
    title: "勇敢尝鲜章",
    icon: "🥢",
    tone: "bg-emerald-100 text-emerald-900",
  },
  {
    title: "闽食小勇士章",
    icon: "🚂",
    tone: "bg-amber-100 text-amber-900",
  },
  {
    title: "食材发现章",
    icon: "🧺",
    tone: "bg-cyan-100 text-cyan-900",
  },
  {
    title: "文明进餐章",
    icon: "🍽️",
    tone: "bg-emerald-100 text-emerald-900",
  },
  {
    title: "好习惯判断章",
    icon: "🟢",
    tone: "bg-teal-100 text-teal-900",
  },
  {
    title: "闽食宣传员",
    icon: "📣",
    tone: "bg-cyan-100 text-cyan-900",
  },
  {
    title: "喝水小勇士",
    icon: "💧",
    tone: "bg-teal-100 text-teal-900",
  },
];

export const mealPhotoChecklist = [
  "先拍清楚整张餐盘，再上传到网站。",
  "餐盘边缘和食物都尽量拍完整。",
  "拍完后请孩子说一句最想介绍的食物。",
];

export const teacherTasks = [
  {
    id: "home",
    label: "一日常规跟进建议",
    starter: "年龄段：中班 4-5 岁。场景：饭前洗手、喝水、排队或整理反复需要提醒。请根据幼儿互动记录生成明日跟进口令、教师观察点和一个可同步家长的小步骤。",
  },
  {
    id: "food-follow",
    label: "闽食进餐/挑食观察建议",
    starter: "年龄段：中班 4-5 岁。幼儿正在认识某种食物。请生成温和食育策略，包含原因理解、靠近小步、课堂小活动和家园同步话术，不贴挑食标签。",
  },
  {
    id: "activity",
    label: "课堂活动方案",
    starter: "年龄段：中班 4-5 岁。活动时长：15-20 分钟。主题：饭前洗手。幼儿已有经验：知道要洗手，但步骤容易漏。希望目标：能按顺序说出并模仿洗手步骤。",
  },
  {
    id: "story",
    label: "故事/绘本引导",
    starter: "请为 4-5 岁幼儿生成一个 3 分钟内可以讲完的互动故事或绘本导入，围绕生活常规或泉州食育，语言温柔、有提问、有结尾小任务。",
  },
  {
    id: "parent-sync",
    label: "家园同步话术",
    starter: "请根据幼儿今天的互动记录，生成一段给家长看的同步话术：孩子完成了什么、老师温和观察到什么、回家可以轻轻做哪一步。",
  },
  {
    id: "encouragement",
    label: "鼓励语",
    starter: "请生成一句适合老师对幼儿说的正向鼓励语，要说具体行为，不比较、不催促，并给出下一小步。",
  },
  {
    id: "child-expression",
    label: "幼儿表达回应建议",
    starter: "请根据幼儿对老师说的话，生成一句温和回应、一个可继续追问的问题和一个安全可完成的小任务。",
  },
  {
    id: "individual-observation",
    label: "个别幼儿观察记录",
    starter: "请根据单个幼儿的今日互动、表达和食物靠近小步，生成个别观察摘要、教师跟进建议和家园同步提醒。",
  },
  {
    id: "class-summary",
    label: "班级数据分析摘要",
    starter: "请根据班级今日互动数据生成数据摘要：参与人数、习惯打卡、阅读打卡、食物观察、重点幼儿和明日跟进重点。",
  },
  {
    id: "parent-reading",
    label: "亲子阅读延伸",
    starter: "请根据教师确认发布的原创绘本，生成亲子共读问题、家庭小任务和家长一句观察提示。",
  },
];

export const washSteps = [
  "打湿小手",
  "抹上泡泡",
  "搓搓手心手背",
  "冲洗干净",
  "擦干小手",
];

export const queueOrder = ["小队长举牌", "第一位小朋友", "第二位小朋友", "第三位小朋友"];

export const minnanFoodObserveSteps = [
  {
    label: "认名字",
    food: "泉州美食",
    icon: "🏷️",
    picture: "🏮",
    cue: "先把美食名字轻轻念一遍。",
  },
  {
    label: "找食材",
    food: "泉州美食",
    icon: "🧺",
    picture: "🥬",
    cue: "找一找它身体里的食材卡。",
  },
  {
    label: "看样子",
    food: "泉州美食",
    icon: "👀",
    picture: "🎨",
    cue: "说说它的颜色、形状或样子。",
  },
  {
    label: "听故事",
    food: "泉州美食",
    icon: "📖",
    picture: "🏠",
    cue: "听一听它常在哪里出现。",
  },
  {
    label: "说发现",
    food: "泉州美食",
    icon: "💬",
    picture: "⭐",
    cue: "说一句我看到了什么。",
  },
  {
    label: "选小步",
    food: "泉州美食",
    icon: "🫶",
    picture: "🥄",
    cue: "选看一看、闻一闻、碰一碰或尝一点点。",
  },
];

export const minnanFoodKnowledge = [
  {
    label: "海蛎",
    intro: "海蛎是泉州海边常见的小海味，圆圆软软，常出现在海蛎煎里。",
    ingredients: ["海蛎"],
    clue: "灰白小颗、海边鲜味。",
    approach: "先看一看形状，再闻一闻蛋香，不急着入口。",
    homeTask: "回家找一找海蛎煎里有没有海蛎，说出名字就完成一步。",
  },
  {
    label: "紫菜",
    intro: "紫菜像薄薄的小海叶，常在紫菜汤里漂起来。",
    ingredients: ["紫菜", "汤"],
    clue: "深紫色、薄薄的、在汤里会散开。",
    approach: "先看颜色，再喝一小口汤或说出名字。",
    homeTask: "晚餐看到汤时，找一找有没有紫菜。",
  },
  {
    label: "芥菜",
    intro: "芥菜是泉州家常饭菜里的绿色朋友，也会和米饭一起做成芥菜饭。",
    ingredients: ["芥菜", "米饭"],
    clue: "绿色叶子、切成小段。",
    approach: "先找绿色小叶子，再说它叫芥菜。",
    homeTask: "家里吃青菜时，请孩子找一种绿色叶子。",
  },
  {
    label: "蛏子",
    intro: "蛏子来自海边，有长长的壳，泉州餐桌上常能见到。",
    ingredients: ["蛏子"],
    clue: "长长壳、海边味。",
    approach: "先看壳的形状，愿意的话闻一闻。",
    homeTask: "看到海鲜时，说说它的形状是长的还是圆的。",
  },
  {
    label: "炸枣",
    intro: "炸枣是闽南传统小点心，圆圆的，外面香香，里面常有甜甜馅。",
    ingredients: ["糯米粉", "馅料"],
    clue: "圆圆金黄、像小球。",
    approach: "先看圆圆样子，再闻一闻香味。",
    homeTask: "遇到传统点心时，介绍它的颜色和形状。",
  },
  {
    label: "芥菜饭",
    intro: "芥菜饭把米饭和芥菜放在一起，是泉州家常味道。",
    ingredients: ["米饭", "芥菜"],
    clue: "白白米饭里有绿色芥菜。",
    approach: "先找绿色芥菜，再尝旁边一小口米饭。",
    homeTask: "饭桌上找一找米饭里有没有绿色食材。",
  },
  {
    label: "海蛎煎",
    intro: "海蛎煎是泉州常见小吃，金黄金黄，里面有海蛎、鸡蛋和地瓜粉。",
    ingredients: ["海蛎", "鸡蛋", "地瓜粉", "小葱"],
    clue: "金黄边、圆圆饼、能看到小葱点。",
    approach: "先看金黄边、闻蛋香，再尝一点点边边。",
    homeTask: "给家人介绍海蛎煎里的一种食材。",
  },
  {
    label: "面线糊",
    intro: "面线糊是泉州早餐里的暖暖味道，细细软软，适合用勺子慢慢看。",
    ingredients: ["面线", "汤", "葱花"],
    clue: "细细面线、热热汤、软软口感。",
    approach: "先用勺子搅一搅，再说出看到的细面线。",
    homeTask: "早餐时说一句：我看到细细的面线。",
  },
  {
    label: "香菇",
    intro: "香菇像一把小伞，气味比较明显，很多孩子可以先从看和闻开始。",
    ingredients: ["香菇"],
    clue: "小伞形状、棕色、气味明显。",
    approach: "先看小伞形状，再远远闻一闻。",
    homeTask: "今晚不用催入口，只找一找香菇在哪里。",
  },
  {
    label: "小葱",
    intro: "小葱是绿色细细的小香味，常点在汤和海蛎煎上。",
    ingredients: ["小葱"],
    clue: "绿色细条、小小葱花。",
    approach: "先找葱花点点，再说出名字。",
    homeTask: "饭桌上找绿色小葱花，说出名字就完成一步。",
  },
  {
    label: "蒜",
    intro: "蒜有明显气味，常帮助菜变香，可以先远远认识它。",
    ingredients: ["蒜"],
    clue: "白色小瓣、气味冲。",
    approach: "先看白色小瓣，再远远闻一闻。",
    homeTask: "家长做饭时，让孩子远远看一看蒜瓣，不急着尝。",
  },
];

export const minnanFoodClues = [
  {
    label: "泉州海蛎煎",
    icon: "🦪",
    stall: "海边鲜味摊",
    clue: "金黄金黄，有海蛎和蛋香。",
    pictureHint: "找圆圆金黄的小饼。",
    colorShape: "金黄边、圆圆饼、能看到小葱点。",
    ingredients: ["海蛎", "鸡蛋", "地瓜粉", "小葱"],
    ingredientIntro: "海蛎带来海味，鸡蛋和地瓜粉让边边变得金黄软糯。",
    cultureStory: "在泉州海边，家人常把新鲜海味做成热乎乎的小吃。",
    gentleTryTip: "如果还不熟悉海蛎口感，可以先看金黄边、闻蛋香，再尝很小一口边边。",
    approachSteps: ["看金黄边", "闻蛋香", "碰一碰边边", "尝一点点"],
  },
  {
    label: "面线糊",
    icon: "🥣",
    stall: "古城小吃摊",
    clue: "细细软软，热热的一碗糊。",
    pictureHint: "找白白细细的面线和小勺子。",
    colorShape: "白白软软、细细长长、像温暖的小汤。",
    ingredients: ["面线", "清汤", "葱花", "少量海味配料"],
    ingredientIntro: "面线细细的，放进热汤里会变得软软滑滑，适合用小勺慢慢认识。",
    cultureStory: "泉州古城早晨常能看到热乎乎的面线糊，是很多家庭熟悉的早餐味道。",
    gentleTryTip: "如果第一次见面线糊，可以先用勺子搅一搅，看细面线在汤里游。",
    approachSteps: ["看细面线", "闻热汤香", "用勺搅一搅", "尝一小勺"],
  },
  {
    label: "土笋冻",
    icon: "🧊",
    stall: "海边鲜味摊",
    clue: "凉凉透明，像小果冻。",
    pictureHint: "找透明小圆冻和酱料点。",
    colorShape: "透明、圆圆、凉凉弹弹。",
    ingredients: ["土笋冻原料", "清汤冻", "蒜蓉酱", "香菜"],
    ingredientIntro: "土笋冻看起来像小果冻，是泉州很有名的海边小吃，可以先观察它透明的样子。",
    cultureStory: "在泉州小吃摊，土笋冻常被装在小碟里，大家会先看看它晶亮的样子。",
    gentleTryTip: "如果还不熟悉，可以先看透明颜色，轻轻碰一碰小碟边，不急着入口。",
    approachSteps: ["看透明样子", "碰小碟边", "闻一闻酱香", "尝一点点冻"],
  },
  {
    label: "闽南肉粽",
    icon: "🍙",
    stall: "家常饭菜摊",
    clue: "粽叶包着香香米粒。",
    pictureHint: "找三角粽和绿色粽叶。",
    colorShape: "三角形、粽叶绿、米粒亮亮。",
    ingredients: ["糯米", "粽叶", "香菇", "肉丁"],
    ingredientIntro: "粽叶把米粒和食材抱在一起，打开时会闻到香香的家常味。",
    cultureStory: "泉州家庭节日里常会包粽子，孩子可以先认识粽叶和米粒。",
    gentleTryTip: "可以先闻粽叶香，找一找米粒，再尝一点点米饭。",
    approachSteps: ["闻粽叶香", "找米粒", "看三角形", "尝一点米饭"],
  },
  {
    label: "烧肉粽",
    icon: "🍙",
    stall: "家常饭菜摊",
    clue: "粽叶香香，里面有糯米和家常馅料。",
    pictureHint: "找打开的粽叶、亮亮米粒和小块馅料。",
    colorShape: "三角粽、粽叶绿、米粒亮亮。",
    ingredients: ["糯米", "粽叶", "香菇", "肉丁", "花生"],
    ingredientIntro: "烧肉粽也常被叫作闽南肉粽，粽叶包着糯米和馅料，闻起来香香的。",
    cultureStory: "泉州家里包粽子时，大人会一层一层把米粒和馅料放进粽叶里。",
    gentleTryTip: "可以先闻粽叶香，再找米粒和香菇，愿意的话尝一点点米饭。",
    approachSteps: ["闻粽叶香", "找米粒", "看三角粽", "尝一点米饭"],
  },
  {
    label: "润饼菜",
    icon: "🌯",
    stall: "古城小吃摊",
    clue: "薄薄饼皮卷着好多菜。",
    pictureHint: "找卷起来的小饼和五颜六色的菜。",
    colorShape: "卷卷的、长长的、里面颜色很多。",
    ingredients: ["薄饼皮", "胡萝卜", "包菜", "花生碎"],
    ingredientIntro: "润饼菜把蔬菜卷进薄饼里，像给食材盖上一条软软小被子。",
    cultureStory: "泉州人常在节日或家人团聚时吃润饼菜，边卷边聊很热闹。",
    gentleTryTip: "如果不熟悉，可以先看里面的颜色，找一种自己认识的蔬菜。",
    approachSteps: ["看颜色", "找蔬菜", "闻花生香", "咬一点饼皮"],
  },
  {
    label: "石花膏",
    icon: "🍧",
    stall: "甜甜清凉摊",
    clue: "清清凉凉，像透明小甜冻。",
    pictureHint: "找小碗里的透明冻和甜汤。",
    colorShape: "透明、细滑、凉凉的甜碗。",
    ingredients: ["石花膏", "蜂蜜水", "水果丁", "少量坚果"],
    ingredientIntro: "石花膏是泉州常见清凉甜品，透明滑滑，可以先用勺子看一看。",
    cultureStory: "天气热的时候，家人会带孩子吃一碗清凉甜甜的石花膏。",
    gentleTryTip: "可以先看透明冻晃一晃，再尝一小勺甜汤。",
    approachSteps: ["看透明冻", "用勺晃一晃", "闻甜香", "尝一小勺"],
  },
  {
    label: "炸醋肉",
    icon: "🥢",
    stall: "家常饭菜摊",
    clue: "外面酥酥，闻起来有一点香香酸味。",
    pictureHint: "找金黄小块和小筷子。",
    colorShape: "金黄小块、外面酥酥。",
    ingredients: ["猪肉", "地瓜粉", "香醋", "蒜香调味"],
    ingredientIntro: "炸醋肉外面裹着地瓜粉，炸好后金黄金黄，味道带一点闽南香。",
    cultureStory: "泉州家常饭桌上常见炸醋肉，大人会夹成小块让孩子慢慢认识。",
    gentleTryTip: "可以先闻一闻香气，看看金黄外皮，再尝很小一块。",
    approachSteps: ["看金黄块", "闻香味", "夹一小块", "尝一点点"],
  },
  {
    label: "崇武鱼卷",
    icon: "🐟",
    stall: "海边鲜味摊",
    clue: "白白圆圆，里面有鱼肉香。",
    pictureHint: "找白色圆片和海边小鱼。",
    colorShape: "白白圆片、软软弹弹。",
    ingredients: ["鱼肉", "地瓜粉", "葱花", "清汤"],
    ingredientIntro: "崇武鱼卷把鱼肉做成圆圆卷片，放进汤里会有清清的海味。",
    cultureStory: "惠安崇武靠海，鱼卷是当地很有代表性的家乡味。",
    gentleTryTip: "如果第一次见鱼卷，可以先看圆片，再喝一小口清汤。",
    approachSteps: ["看圆片", "闻清汤", "找葱花", "尝一点鱼卷"],
  },
  {
    label: "姜母鸭",
    icon: "🦆",
    stall: "家常滋补摊",
    clue: "姜片香香，鸭肉热乎乎。",
    pictureHint: "找深色鸭肉和一片片老姜。",
    colorShape: "深褐色小块、姜片黄黄、热气香香。",
    ingredients: ["鸭肉", "老姜", "芝麻油", "米酒香料"],
    ingredientIntro: "姜母鸭用鸭肉和老姜慢慢煮，姜片香香，可以先看颜色、闻一闻。",
    cultureStory: "天气凉的时候，泉州家人会围在一起吃热热的姜母鸭。",
    gentleTryTip: "如果姜味有点明显，可以先看姜片，再闻一闻汤香，不急着尝。",
    approachSteps: ["看姜片", "闻汤香", "碰一碰小碗", "尝一点汤"],
  },
  {
    label: "芋头饼",
    icon: "🟣",
    stall: "甜甜糕点摊",
    clue: "圆圆香香，里面有芋头。",
    pictureHint: "找圆圆小饼和淡紫色芋泥。",
    colorShape: "圆圆饼、外皮金黄、里面淡紫。",
    ingredients: ["芋头", "糯米粉", "芝麻", "少量糖"],
    ingredientIntro: "芋头饼把芋头做成软软馅，外面圆圆香香，可以先看切面颜色。",
    cultureStory: "泉州点心摊常能看到芋头做的小点心，适合慢慢认识。",
    gentleTryTip: "可以先看紫紫芋头馅，闻一闻香味，再咬一点点边边。",
    approachSteps: ["看圆饼", "闻甜香", "碰一碰边边", "尝一点边边"],
  },
  {
    label: "牛肉羹",
    icon: "🥣",
    stall: "古城暖汤摊",
    clue: "热热一碗，牛肉软软滑滑。",
    pictureHint: "找小碗热汤和牛肉片。",
    colorShape: "汤色暖暖、小片牛肉、勺子舀起来滑滑。",
    ingredients: ["牛肉", "地瓜粉", "清汤", "香菜"],
    ingredientIntro: "牛肉羹把牛肉做得软软滑滑，热汤可以给身体一点暖暖力气。",
    cultureStory: "泉州古城小吃里常有热热的牛肉羹，大家会用小勺慢慢喝。",
    gentleTryTip: "可以先看小勺里的汤，再闻一闻香味，愿意就尝一点汤。",
    approachSteps: ["看热汤", "闻香味", "用勺碰一碰", "尝一点汤"],
  },
  {
    label: "洪濑鸡爪",
    icon: "🍗",
    stall: "家常卤味摊",
    clue: "颜色深深，卤香明显。",
    pictureHint: "找小鸡爪和深色卤汁。",
    colorShape: "深褐色、小爪形、表面亮亮。",
    ingredients: ["鸡爪", "卤汁", "香料", "少量蒜香"],
    ingredientIntro: "洪濑鸡爪是泉州周边很有名的卤味，可以先观察形状和颜色。",
    cultureStory: "南安洪濑的卤味很有名，家人有时会把鸡爪切小让孩子认识。",
    gentleTryTip: "如果形状有点陌生，可以先看颜色和纹路，只说出名字也很好。",
    approachSteps: ["看形状", "闻卤香", "碰一碰小盘", "尝一点点肉"],
  },
  {
    label: "四果汤",
    icon: "🍨",
    stall: "甜甜清凉摊",
    clue: "清凉甜甜，有好多小配料。",
    pictureHint: "找透明甜汤、彩色水果和小勺。",
    colorShape: "清清凉凉、颜色很多、小碗甜汤。",
    ingredients: ["水果丁", "石花膏", "红豆", "蜂蜜水"],
    ingredientIntro: "四果汤里有水果和清凉小配料，颜色多，可以先找自己认识的一种。",
    cultureStory: "泉州夏天常见四果汤，大家会按喜欢的配料舀成一碗。",
    gentleTryTip: "可以先找一个认识的水果丁，再尝一小口甜汤。",
    approachSteps: ["看颜色", "找水果", "舀一舀", "尝一点甜汤"],
  },
  {
    label: "咸饭",
    icon: "🍚",
    stall: "家常饭菜摊",
    clue: "米粒香香，里面藏着菜和香菇。",
    pictureHint: "找一碗米饭、香菇和蔬菜丁。",
    colorShape: "米粒一颗颗、颜色家常、香菇小伞藏里面。",
    ingredients: ["米饭", "香菇", "胡萝卜", "青菜"],
    ingredientIntro: "咸饭把米饭和家常食材一起煮，能看到不同颜色的小配料。",
    cultureStory: "泉州家庭常做咸饭，一锅饭里有米粒、菜和家里的味道。",
    gentleTryTip: "可以先找米粒和香菇，不喜欢配料也可以先尝一口米饭。",
    approachSteps: ["看米粒", "找香菇", "闻饭香", "尝一口米饭"],
  },
  {
    label: "香菇",
    icon: "🍄",
    stall: "食材观察台",
    clue: "小伞一样，闻起来有特别香味。",
    pictureHint: "找棕色小伞和菇盖纹路。",
    colorShape: "棕色、像小伞、切开会有纹路。",
    ingredients: ["香菇", "清汤", "米饭或肉粽"],
    ingredientIntro: "香菇是很多闽南家常菜里的香味食材，味道比较明显，可以先看样子和闻一闻。",
    cultureStory: "泉州家常饭菜、肉粽或汤里常会看到香菇，它会让饭菜更香。",
    gentleTryTip: "如果不喜欢香菇味，可以先找小伞形状，再闻一下，不急着吃。",
    approachSteps: ["看小伞", "闻一闻", "摸一摸边边", "尝米饭里的香味"],
  },
  {
    label: "小葱",
    icon: "🌿",
    stall: "食材观察台",
    clue: "绿绿细细，常常撒在汤和面线糊上。",
    pictureHint: "找绿色小圈圈或细细葱花。",
    colorShape: "绿色、细细碎碎、像小圆圈。",
    ingredients: ["小葱", "清汤", "面线糊"],
    ingredientIntro: "小葱常被切成小葱花，撒在汤、面线糊或鱼卷里，颜色很明显。",
    cultureStory: "很多泉州热汤和小吃上会撒一点葱花，让香味更明显。",
    gentleTryTip: "如果看到绿色葱花有点担心，可以先用勺子找一找、闻一闻，再决定靠近哪一步。",
    approachSteps: ["找绿色小圈", "闻葱香", "用勺拨一拨", "尝一点汤"],
  },
  {
    label: "蒜",
    icon: "🧄",
    stall: "食材观察台",
    clue: "白白小瓣，味道比较明显。",
    pictureHint: "找白色小蒜瓣或蒜蓉点。",
    colorShape: "白色、小瓣、切碎后像小点点。",
    ingredients: ["蒜", "蒜蓉酱", "家常调味"],
    ingredientIntro: "蒜常被做成蒜蓉或调味，味道很明显，孩子可以先认识名字和气味。",
    cultureStory: "泉州小吃有时会搭配蒜蓉酱，先认识它的味道也是一种食育探索。",
    gentleTryTip: "如果觉得蒜味很冲，可以先远远闻一闻，说出它的名字就很好。",
    approachSteps: ["看白色小瓣", "远远闻一闻", "找蒜蓉点", "说出名字"],
  },
];

export const foodTrainStations = [
  {
    label: "泉州海蛎煎",
    icon: "🦪",
    station: "海边金黄站",
    chant: "海蛎煎，金黄边，海味香香进小店。",
    command: "小列车进站，请找到海蛎煎。",
    ingredients: ["海蛎", "鸡蛋", "地瓜粉"],
  },
  {
    label: "面线糊",
    icon: "🥣",
    station: "古城暖汤站",
    chant: "面线糊，细又柔，热热一碗慢慢瞅。",
    command: "小列车进站，请找到面线糊。",
    ingredients: ["面线", "清汤", "葱花"],
  },
  {
    label: "紫菜汤",
    icon: "🌊",
    station: "海风紫菜站",
    chant: "紫菜汤，海风香，小勺轻轻尝一尝。",
    command: "小列车进站，请找到紫菜汤。",
    ingredients: ["紫菜", "清汤", "虾米"],
  },
  {
    label: "芥菜饭",
    icon: "🥬",
    station: "家常绿叶站",
    chant: "芥菜饭，绿叶香，米粒粒粒有力量。",
    command: "小列车进站，请找到芥菜饭。",
    ingredients: ["芥菜", "米饭", "香菇"],
  },
  {
    label: "蛏子",
    icon: "🦪",
    station: "海边贝壳站",
    chant: "小蛏子，住海边，贝壳开合像小船。",
    command: "小列车进站，请找到蛏子。",
    ingredients: ["蛏子", "姜丝", "清汤"],
  },
  {
    label: "炸枣",
    icon: "🟠",
    station: "甜甜糕点站",
    chant: "炸枣圆，香又甜，先看圆圆小笑脸。",
    command: "小列车进站，请找到炸枣。",
    ingredients: ["糯米粉", "豆沙", "芝麻"],
  },
  {
    label: "润饼菜",
    icon: "🌯",
    station: "古城卷卷站",
    chant: "润饼菜，卷起来，蔬菜朋友排成排。",
    command: "小列车进站，请找到润饼菜。",
    ingredients: ["薄饼皮", "包菜", "花生碎"],
  },
  {
    label: "石花膏",
    icon: "🍧",
    station: "清凉甜甜站",
    chant: "石花膏，透明亮，清清凉凉慢慢尝。",
    command: "小列车进站，请找到石花膏。",
    ingredients: ["石花膏", "蜂蜜水", "水果丁"],
  },
  {
    label: "土笋冻",
    icon: "🧊",
    station: "透明小冻站",
    chant: "土笋冻，亮晶晶，先看样子听故事。",
    command: "小列车进站，请找到土笋冻。",
    ingredients: ["土笋冻原料", "清汤冻", "蒜蓉酱"],
  },
  {
    label: "闽南肉粽",
    icon: "🍙",
    station: "粽叶香香站",
    chant: "肉粽香，粽叶包，米粒朋友抱一抱。",
    command: "小列车进站，请找到闽南肉粽。",
    ingredients: ["糯米", "粽叶", "香菇"],
  },
  {
    label: "烧肉粽",
    icon: "🍙",
    station: "粽叶米香站",
    chant: "烧肉粽，粽叶香，米粒朋友抱一旁。",
    command: "小列车进站，请找到烧肉粽。",
    ingredients: ["糯米", "粽叶", "香菇", "肉丁"],
  },
  {
    label: "崇武鱼卷",
    icon: "🐟",
    station: "海边鱼卷站",
    chant: "鱼卷白，圆片片，海边味道慢慢见。",
    command: "小列车进站，请找到崇武鱼卷。",
    ingredients: ["鱼肉", "地瓜粉", "葱花"],
  },
  {
    label: "姜母鸭",
    icon: "🦆",
    station: "姜香暖暖站",
    chant: "姜母鸭，热乎乎，姜片香香慢慢闻。",
    command: "小列车进站，请找到姜母鸭。",
    ingredients: ["鸭肉", "老姜", "芝麻油"],
  },
  {
    label: "炸醋肉",
    icon: "🥢",
    station: "金黄香香站",
    chant: "炸醋肉，金黄块，先看外皮再靠近。",
    command: "小列车进站，请找到炸醋肉。",
    ingredients: ["猪肉", "地瓜粉", "香醋"],
  },
  {
    label: "芋头饼",
    icon: "🟣",
    station: "芋香圆饼站",
    chant: "芋头饼，圆又香，紫紫馅儿藏中央。",
    command: "小列车进站，请找到芋头饼。",
    ingredients: ["芋头", "糯米粉", "芝麻"],
  },
  {
    label: "牛肉羹",
    icon: "🥣",
    station: "古城暖羹站",
    chant: "牛肉羹，热热汤，小勺慢慢看一看。",
    command: "小列车进站，请找到牛肉羹。",
    ingredients: ["牛肉", "清汤", "香菜"],
  },
  {
    label: "洪濑鸡爪",
    icon: "🍗",
    station: "卤香小爪站",
    chant: "鸡爪爪，卤香香，先看形状不慌张。",
    command: "小列车进站，请找到洪濑鸡爪。",
    ingredients: ["鸡爪", "卤汁", "香料"],
  },
  {
    label: "四果汤",
    icon: "🍨",
    station: "清凉甜汤站",
    chant: "四果汤，颜色多，找个水果说一说。",
    command: "小列车进站，请找到四果汤。",
    ingredients: ["水果丁", "石花膏", "蜂蜜水"],
  },
  {
    label: "咸饭",
    icon: "🍚",
    station: "家常米香站",
    chant: "咸饭香，米粒亮，香菇朋友藏饭旁。",
    command: "小列车进站，请找到咸饭。",
    ingredients: ["米饭", "香菇", "青菜"],
  },
];

export const foodGuessRounds = [
  {
    answer: "海蛎",
    icon: "🦪",
    treasure: "海边宝箱",
    hints: ["来自海边", "小小软软", "可以做成泉州海蛎煎"],
    options: ["海蛎", "芥菜", "面线", "鱼肉"],
    praise: "你找到海蛎啦，可以播报：海蛎是海边来的鲜味食材。",
  },
  {
    answer: "面线",
    icon: "🥣",
    treasure: "古城宝箱",
    hints: ["细细长长", "放进热汤里软软的", "可以做成面线糊"],
    options: ["紫菜", "面线", "虾米", "地瓜粉"],
    praise: "你找到面线啦，可以播报：面线细细软软，是面线糊里的主角。",
  },
  {
    answer: "芥菜",
    icon: "🥬",
    treasure: "绿叶宝箱",
    hints: ["绿绿叶子", "有一点清香", "可以和米饭做成芥菜饭"],
    options: ["芥菜", "海蛎", "蛏子", "鱼肉"],
    praise: "你找到芥菜啦，可以播报：芥菜是绿叶食材，能做家常芥菜饭。",
  },
  {
    answer: "地瓜粉",
    icon: "⭐",
    treasure: "小厨师宝箱",
    hints: ["白白细细", "能让边边软糯", "海蛎煎里常见它"],
    options: ["面线", "紫菜", "地瓜粉", "虾米"],
    praise: "你找到地瓜粉啦，可以播报：地瓜粉能让海蛎煎有软糯口感。",
  },
  {
    answer: "香菇",
    icon: "🍄",
    treasure: "香香小伞宝箱",
    hints: ["像一把小伞", "味道比较明显", "肉粽、汤里都可能遇到它"],
    options: ["香菇", "小葱", "蒜", "紫菜"],
    praise: "你找到香菇啦，可以播报：香菇像小伞，先闻一闻、看一看也很勇敢。",
  },
  {
    answer: "小葱",
    icon: "🌿",
    treasure: "绿绿细丝宝箱",
    hints: ["绿绿细细", "常撒在面线糊上", "有一点清香味"],
    options: ["小葱", "芥菜", "海蛎", "地瓜粉"],
    praise: "你找到小葱啦，可以播报：小葱是绿色的小配料，会让食物更香。",
  },
  {
    answer: "蒜",
    icon: "🧄",
    treasure: "白白小瓣宝箱",
    hints: ["白白一瓣一瓣", "味道很明显", "可以做成蒜蓉酱"],
    options: ["蒜", "虾米", "面线", "鱼肉"],
    praise: "你找到蒜啦，可以播报：蒜味道很特别，先认识名字也是进步。",
  },
  {
    answer: "紫菜",
    icon: "🌊",
    treasure: "海风薄片宝箱",
    hints: ["来自海里", "薄薄一片", "可以做成紫菜汤"],
    options: ["紫菜", "面线", "小葱", "芥菜"],
    praise: "你找到紫菜啦，可以播报：紫菜来自海边，放进汤里软软的。",
  },
  {
    answer: "老姜",
    icon: "🫚",
    treasure: "姜香暖暖宝箱",
    hints: ["黄黄一片片", "闻起来有点辣香", "姜母鸭里常见它"],
    options: ["老姜", "水果丁", "石花膏", "米饭"],
    praise: "你找到老姜啦，可以播报：老姜香香暖暖，先闻一闻也很好。",
  },
  {
    answer: "芋头",
    icon: "🟣",
    treasure: "芋香圆饼宝箱",
    hints: ["里面可能是淡紫色", "能做成圆圆小饼", "闻起来香香甜甜"],
    options: ["芋头", "鱼肉", "鸡爪", "小葱"],
    praise: "你找到芋头啦，可以播报：芋头能做成香香的芋头饼。",
  },
  {
    answer: "牛肉",
    icon: "🥩",
    treasure: "暖羹小勺宝箱",
    hints: ["能做成热热的羹", "小片软软滑滑", "牛肉羹里有它"],
    options: ["牛肉", "粽叶", "石花膏", "水果丁"],
    praise: "你找到牛肉啦，可以播报：牛肉羹热热软软，可以先尝一点汤。",
  },
  {
    answer: "鸡爪",
    icon: "🍗",
    treasure: "卤香小爪宝箱",
    hints: ["形状像小爪", "卤过以后颜色深深", "洪濑鸡爪里有它"],
    options: ["鸡爪", "面线", "芋头", "紫菜"],
    praise: "你找到鸡爪啦，可以播报：洪濑鸡爪颜色深深，先看形状就可以。",
  },
  {
    answer: "水果丁",
    icon: "🍍",
    treasure: "清凉甜汤宝箱",
    hints: ["颜色很多", "四果汤里常常见到", "可以用小勺舀一舀"],
    options: ["水果丁", "老姜", "鱼肉", "地瓜粉"],
    praise: "你找到水果丁啦，可以播报：四果汤里有清凉甜甜的小配料。",
  },
  {
    answer: "米饭",
    icon: "🍚",
    treasure: "家常米香宝箱",
    hints: ["一颗一颗白白的", "咸饭里有它", "能和香菇、青菜一起煮"],
    options: ["米饭", "海蛎", "蜂蜜水", "鸡爪"],
    praise: "你找到米饭啦，可以播报：咸饭里有米粒和家常食材。",
  },
];

export const mealMannerActions = [
  {
    label: "小手扶好碗",
    icon: "🥣",
    command: "小手扶好碗，饭菜不乱跑。",
  },
  {
    label: "小脚放稳",
    icon: "🪑",
    command: "小脚放稳稳，身体坐舒服。",
  },
  {
    label: "嘴巴轻轻嚼",
    icon: "🥢",
    command: "嘴巴轻轻嚼，细嚼慢慢咽。",
  },
  {
    label: "食物不乱撒",
    icon: "🧻",
    command: "饭菜慢慢送入口，食物尽量不乱撒。",
  },
  {
    label: "餐后会整理",
    icon: "🧺",
    command: "餐后收一收，碗筷桌面都有家。",
  },
  {
    label: "轻声说需要",
    icon: "🤲",
    command: "想添饭、想喝水，轻声告诉老师。",
  },
  {
    label: "愿意靠近一步",
    icon: "🌱",
    command: "陌生食物先看一看、闻一闻，愿意靠近就是进步。",
  },
  {
    label: "感谢做饭人",
    icon: "💛",
    command: "吃到饭菜说谢谢，记得有人辛苦做出来。",
  },
];

export const habitTrafficLightCards = [
  {
    behavior: "饭前洗手",
    icon: "🧼",
    answer: "green",
    goodPractice: "饭前洗手是好习惯，小手干净再用餐。",
  },
  {
    behavior: "边吃边玩",
    icon: "🧸",
    answer: "red",
    goodPractice: "这个做法需要换一换，我们可以这样做：吃饭时先照顾小肚子，玩具等一等。",
  },
  {
    behavior: "细嚼慢咽",
    icon: "🥢",
    answer: "green",
    goodPractice: "慢慢嚼、轻轻咽，身体更舒服。",
  },
  {
    behavior: "撒饭不收拾",
    icon: "🍚",
    answer: "red",
    goodPractice: "这个做法需要换一换，我们可以这样做：不小心撒了饭，可以请老师帮忙一起整理。",
  },
  {
    behavior: "看完书放回书架",
    icon: "📚",
    answer: "green",
    goodPractice: "看完书放回书架，是照顾图书的好习惯。",
  },
  {
    behavior: "上课时大声打断别人",
    icon: "🙋",
    answer: "red",
    goodPractice: "这个做法需要换一换，我们可以这样做：先举小手，等老师看到再轻声说。",
  },
  {
    behavior: "生气时说“我有点难过”",
    icon: "🌤️",
    answer: "green",
    goodPractice: "能说出自己的心情，是照顾自己的好办法。",
  },
  {
    behavior: "拿着水杯跑来跑去",
    icon: "🥤",
    answer: "red",
    goodPractice: "这个做法需要换一换，我们可以这样做：拿水杯时慢慢走，坐稳再喝水。",
  },
  {
    behavior: "愿意先看一看陌生菜",
    icon: "👀",
    answer: "green",
    goodPractice: "愿意先看一看、闻一闻，就是靠近新食物的一小步。",
  },
  {
    behavior: "把不爱吃的菜偷偷丢掉",
    icon: "🗑️",
    answer: "red",
    goodPractice: "这个做法需要换一换，我们可以告诉老师：我还在认识它，先试一小步。",
  },
  {
    behavior: "听完故事说一个角色",
    icon: "📖",
    answer: "green",
    goodPractice: "听完故事能说一个角色，说明小耳朵和小脑袋都在认真工作。",
  },
  {
    behavior: "图书看完随手放地上",
    icon: "📚",
    answer: "red",
    goodPractice: "这个做法需要换一换，看完书要送回书架，让下一位小朋友也能找到。",
  },
];

export const foodPreferenceReasons = [
  {
    label: "味道重",
    icon: "👃",
    strategy: "先承认味道比较明显，允许孩子先看一看、闻一闻，不急着入口。",
  },
  {
    label: "气味冲",
    icon: "🌬️",
    strategy: "先远远闻一闻，说出这是什么气味，再选择是否靠近一点。",
  },
  {
    label: "口感怪",
    icon: "🥄",
    strategy: "先摸一摸或看一看口感特点，也可以只尝一点汤汁或旁边米饭。",
  },
  {
    label: "颜色不熟悉",
    icon: "🎨",
    strategy: "请孩子找一找颜色、形状和食材名字，把陌生感变成观察任务。",
  },
  {
    label: "太硬",
    icon: "🥕",
    strategy: "先看形状和颜色，必要时请成人切小、煮软，再由孩子选择一小步。",
  },
  {
    label: "太滑",
    icon: "🥣",
    strategy: "先用勺子看一看、碰一碰，等孩子熟悉后再尝一点点。",
  },
  {
    label: "今天没胃口",
    icon: "☁️",
    strategy: "先接纳状态，保留少量尝试机会，不用催促或贴标签。",
  },
  {
    label: "以前没吃过",
    icon: "❔",
    strategy: "把陌生感变成认识任务：先说名字、找食材，再选择一个靠近小步。",
  },
];

export const foodPreferenceApproachSteps = [
  "看一看",
  "闻一闻",
  "碰一碰",
  "尝一点汤汁",
  "尝旁边米饭",
  "说出名字",
];

export const peerEncouragementPrompts = [
  {
    peer: "小伙伴正在认识海蛎煎",
    icon: "🧒",
    foodIcon: "🦪",
    encouragement: "我陪你先找金黄边。",
  },
  {
    peer: "小伙伴第一次看土笋冻",
    icon: "👧",
    foodIcon: "🧊",
    encouragement: "我们先看透明样子。",
  },
  {
    peer: "小伙伴想介绍润饼菜",
    icon: "👦",
    foodIcon: "🌯",
    encouragement: "我听你说里面的菜。",
  },
];

export const foodReporterFoods = [
  {
    label: "泉州海蛎煎",
    icon: "🦪",
    imageKey: "shijing-haolijian",
    ingredientText: "里面有海蛎、鸡蛋、地瓜粉和小葱。",
    discoveryText: "金黄金黄，边边香香，像海边来的小饼。",
    reporterLine: "大家好，我介绍的是泉州海蛎煎。它金黄金黄，里面有海蛎和鸡蛋，是泉州海边的香香味道。",
  },
  {
    label: "面线糊",
    icon: "🥣",
    imageKey: "mianxianhu",
    ingredientText: "里面有细细的面线、热汤和葱花。",
    discoveryText: "细细软软，热乎乎，常在早餐时候出现。",
    reporterLine: "大家好，我介绍的是面线糊。它细细软软，里面有面线和葱花，是泉州早餐里的暖暖味道。",
  },
  {
    label: "润饼菜",
    icon: "🌯",
    imageKey: "runbing",
    ingredientText: "里面有薄饼皮、蔬菜和一点点家常配料。",
    discoveryText: "卷起来像小被子，能看到很多颜色。",
    reporterLine: "大家好，我介绍的是润饼菜。它用薄饼皮卷起蔬菜，颜色很多，是泉州家常的清爽味道。",
  },
  {
    label: "石花膏",
    icon: "🍧",
    imageKey: "shihuagao",
    ingredientText: "用石花草做成透明清凉的小甜品。",
    discoveryText: "透明、凉凉、会轻轻晃，夏天很常见。",
    reporterLine: "大家好，我介绍的是石花膏。它透明凉凉，是泉州夏天常见的清凉甜品。",
  },
  {
    label: "土笋冻",
    icon: "🧊",
    imageKey: "tusundong",
    ingredientText: "来自海边食材，做成透明弹弹的小冻。",
    discoveryText: "圆圆透明，凉凉弹弹，可以先看样子。",
    reporterLine: "大家好，我介绍的是土笋冻。它透明弹弹，是泉州海边常见的特别小吃。",
  },
  {
    label: "崇武鱼卷",
    icon: "🐟",
    imageKey: "yujuan",
    ingredientText: "里面有鱼肉，卷成圆圆长长的样子。",
    discoveryText: "白白圆圆，切开像小圆片，常放在汤里。",
    reporterLine: "大家好，我介绍的是崇武鱼卷。它用鱼肉做成，圆圆白白，是泉州海边的鲜味。",
  },
  {
    label: "闽南肉粽",
    icon: "🍙",
    imageKey: "shaorouzong",
    ingredientText: "里面有糯米、粽叶、香菇和家常配料。",
    discoveryText: "三角形，粽叶香，打开能看到亮亮米粒。",
    reporterLine: "大家好，我介绍的是闽南肉粽。它用粽叶包着米粒和香菇，是泉州家常的香香味道。",
  },
  {
    label: "姜母鸭",
    icon: "🦆",
    imageKey: "jiangmuya",
    ingredientText: "里面有鸭肉、老姜和香香汤汁。",
    discoveryText: "热乎乎，姜片黄黄，闻起来很香。",
    reporterLine: "大家好，我介绍的是姜母鸭。它有鸭肉和老姜，热热香香，是泉州家人围坐时的味道。",
  },
  {
    label: "烧肉粽",
    icon: "🍙",
    imageKey: "shaorouzong",
    ingredientText: "里面有糯米、粽叶、香菇和肉丁。",
    discoveryText: "粽叶香香，米粒亮亮，打开像一个小宝包。",
    reporterLine: "大家好，我介绍的是烧肉粽。它也叫闽南肉粽，粽叶包着米粒和家常馅料。",
  },
  {
    label: "炸醋肉",
    icon: "🥢",
    imageKey: "quanzhou-curou",
    ingredientText: "里面有猪肉、地瓜粉和一点香醋味。",
    discoveryText: "金黄金黄，外面酥酥，是家常饭桌上的香味。",
    reporterLine: "大家好，我介绍的是炸醋肉。它金黄金黄，外皮香香，可以先看一看再靠近。",
  },
  {
    label: "芋头饼",
    icon: "🟣",
    imageKey: "yutoubing",
    ingredientText: "里面有芋头、糯米粉和一点芝麻香。",
    discoveryText: "圆圆小饼，切开可能看到淡紫色芋泥。",
    reporterLine: "大家好，我介绍的是芋头饼。它圆圆香香，里面有软软的芋头。",
  },
  {
    label: "牛肉羹",
    icon: "🥣",
    imageKey: "niurougeng",
    ingredientText: "里面有牛肉、清汤和一点香菜。",
    discoveryText: "热热一碗，小勺舀起来软软滑滑。",
    reporterLine: "大家好，我介绍的是牛肉羹。它热乎乎，牛肉软软，可以先尝一点汤。",
  },
  {
    label: "洪濑鸡爪",
    icon: "🍗",
    imageKey: "honglai-jizhua",
    ingredientText: "里面有鸡爪、卤汁和香料。",
    discoveryText: "颜色深深，形状特别，闻起来是卤香味。",
    reporterLine: "大家好，我介绍的是洪濑鸡爪。它是泉州周边有名的卤味，可以先观察形状。",
  },
  {
    label: "四果汤",
    icon: "🍨",
    imageKey: "siguotang",
    ingredientText: "里面有水果丁、石花膏和甜甜汤水。",
    discoveryText: "颜色很多，清凉甜甜，适合用小勺慢慢看。",
    reporterLine: "大家好，我介绍的是四果汤。它清凉甜甜，里面有好多小配料。",
  },
  {
    label: "咸饭",
    icon: "🍚",
    imageKey: "xianfan",
    ingredientText: "里面有米饭、香菇、青菜和家常配料。",
    discoveryText: "米粒香香，里面藏着不同颜色的小食材。",
    reporterLine: "大家好，我介绍的是咸饭。它把米饭和家常食材煮在一起，是泉州家里的香味。",
  },
];

export const foodKitchenRecipes = [
  {
    label: "泉州海蛎煎",
    icon: "🦪",
    area: "海边鲜味小厨房",
    actions: ["洗一洗海蛎", "拌一拌鸡蛋和地瓜粉", "煎一煎金黄边", "摆一摆小盘子"],
    chant: "洗一洗，拌一拌，煎出金黄边，小厨师请上盘。",
  },
  {
    label: "面线糊",
    icon: "🥣",
    area: "古城早餐小厨房",
    actions: ["看一看细面线", "搅一搅热汤", "盛一盛小碗", "说一句暖暖的"],
    chant: "细面线，热汤汤，慢慢搅，轻轻尝。",
  },
  {
    label: "润饼菜",
    icon: "🌯",
    area: "家常卷卷小厨房",
    actions: ["铺一铺薄饼皮", "放一放蔬菜", "卷一卷食材", "介绍一下颜色"],
    chant: "薄饼皮，蔬菜彩，卷一卷，介绍来。",
  },
  {
    label: "石花膏",
    icon: "🍧",
    area: "甜甜清凉小厨房",
    actions: ["舀一舀石花膏", "加一加清甜水", "拌一拌小勺子", "分享一句发现"],
    chant: "透明冻，轻轻晃，拌一拌，清凉香。",
  },
  {
    label: "闽南肉粽",
    icon: "🍙",
    area: "粽叶香香小厨房",
    actions: ["看一看粽叶", "找一找米粒", "闻一闻香菇味", "介绍一下形状"],
    chant: "粽叶包，米粒亮，闻一闻，香香香。",
  },
  {
    label: "姜母鸭",
    icon: "🦆",
    area: "姜香暖暖小厨房",
    actions: ["看一看老姜片", "摆一摆鸭肉块", "闻一闻热汤香", "说一句暖暖的"],
    chant: "姜片香，鸭肉暖，先闻一闻不着急。",
  },
  {
    label: "烧肉粽",
    icon: "🍙",
    area: "粽叶米香小厨房",
    actions: ["看一看粽叶", "找一找米粒", "摆一摆小馅料", "介绍一下三角粽"],
    chant: "粽叶开，米粒亮，烧肉粽里藏家乡。",
  },
  {
    label: "土笋冻",
    icon: "🧊",
    area: "透明观察小厨房",
    actions: ["看一看透明冻", "点一点小碟边", "闻一闻酱香", "说一句像什么"],
    chant: "透明冻，亮晶晶，先看一看也很行。",
  },
  {
    label: "炸醋肉",
    icon: "🥢",
    area: "金黄香香小厨房",
    actions: ["看一看金黄块", "摆一摆小盘子", "闻一闻香香味", "说一句脆脆的"],
    chant: "金黄块，香喷喷，先闻一闻再靠近。",
  },
  {
    label: "芋头饼",
    icon: "🟣",
    area: "芋香点心小厨房",
    actions: ["看一看圆饼", "找一找芋头馅", "撒一撒芝麻", "介绍一下颜色"],
    chant: "芋头饼，圆又香，紫紫芋头在中央。",
  },
  {
    label: "牛肉羹",
    icon: "🥣",
    area: "古城暖羹小厨房",
    actions: ["看一看牛肉片", "搅一搅热汤", "舀一舀小勺", "说一句暖暖的"],
    chant: "牛肉羹，热汤汤，小勺慢慢看一看。",
  },
  {
    label: "洪濑鸡爪",
    icon: "🍗",
    area: "卤香观察小厨房",
    actions: ["看一看小爪形", "找一找亮亮卤汁", "闻一闻卤香", "说一句我看到了"],
    chant: "鸡爪爪，卤香香，先看形状不慌张。",
  },
  {
    label: "崇武鱼卷",
    icon: "🐟",
    area: "海边鱼卷小厨房",
    actions: ["看一看鱼卷片", "摆一摆小圆片", "闻一闻清汤", "介绍一下海边味"],
    chant: "鱼卷白，圆片片，海边鲜味慢慢见。",
  },
  {
    label: "四果汤",
    icon: "🍨",
    area: "清凉甜甜小厨房",
    actions: ["找一找水果丁", "舀一舀石花膏", "加一加甜汤", "说一句颜色多"],
    chant: "四果汤，颜色多，小勺轻轻说一说。",
  },
  {
    label: "咸饭",
    icon: "🍚",
    area: "家常米香小厨房",
    actions: ["看一看米粒", "找一找香菇", "拌一拌小饭勺", "介绍一下家常香"],
    chant: "咸饭香，米粒亮，香菇朋友藏饭旁。",
  },
];

export const storyMissionMap: Record<ThemeId, string[]> = {
  habit: ["生活习惯", "进餐习惯", "阅读表达", "安全与情绪"],
  food: ["闽食小列车", "美食猜猜乐", "闽食小小播报员", "泉州小厨房"],
};

export const themeVideoCards: Record<
  ThemeId,
  Array<{
    title: string;
    icon: string;
    description: string;
    topics: string[];
  }>
> = {
  habit: [
    {
      title: "生活习惯小影院",
      icon: "🧼",
      description: "适合播放洗手、排队、如厕等一日生活习惯视频。",
      topics: ["洗手步骤", "排队等待", "如厕整理"],
    },
    {
      title: "安全放松学",
      icon: "🛟",
      description: "适合播放交通安全、饮食安全、防火安全等短视频。",
      topics: ["交通安全", "饮食安全", "防火安全"],
    },
  ],
  food: [
    {
      title: "泉州闽食小课堂",
      icon: "🍽️",
      description: "适合播放食物来源、营养价值、泉州美食做法视频。",
      topics: ["食物来源", "营养价值", "泉州美食做法"],
    },
    {
      title: "非遗文化小剧场",
      icon: "🎬",
      description: "适合播放泉州非遗文化、南音、传统饮食宣传视频。",
      topics: ["泉州非遗", "南音文化", "闽南饮食宣传"],
    },
  ],
};

export const teacherPitchCards = [
  {
    title: "快速活动方案",
    description: "先选主题、年龄和目标，生成适合 3-6 岁幼儿的活动初稿。",
  },
  {
    title: "结构清楚",
    description: "包含目标、材料、流程、提问、观察和家园延伸，方便继续修改。",
  },
  {
    title: "可复制可试播",
    description: "生成结果支持复制、语音试播和二次调整，备课前能快速校对。",
  },
];

export const teacherWorkflowCards = [
  {
    title: "故事导入",
    icon: "📖",
    description: "先生成角色、场景和第一个问题，让幼儿愿意进入活动。",
  },
  {
    title: "活动目标",
    icon: "🎯",
    description: "把习惯培养、食育认知或安全知识转成清楚的小目标。",
  },
  {
    title: "活动流程",
    icon: "🧩",
    description: "生成导入、操作、互动提问和收束环节，老师可以继续调整。",
  },
  {
    title: "观察延伸",
    icon: "📝",
    description: "把儿童互动记录转成观察要点和下一次活动延伸建议。",
  },
];

type TeacherGroupActivityCard = {
  title: string;
  themeId: ThemeId;
  scene: string;
  goal: string;
  steps: string[];
  aiCanGenerate: string;
};

export const teacherGroupActivityCards: TeacherGroupActivityCard[] = [
  {
    title: "文明进餐操",
    themeId: "habit" as const,
    scene: "午餐前、点心前、过渡环节",
    goal: "幼儿能跟随口令模仿扶碗、坐稳、细嚼慢咽和餐后整理动作。",
    steps: ["听动作口令", "模仿一个动作", "说出好习惯", "迁移到午餐环节"],
    aiCanGenerate: "动作口令、节奏儿歌、打卡话术、家园同步建议",
  },
  {
    title: "好习惯红绿牌",
    themeId: "habit" as const,
    scene: "生活习惯集体游戏、安全判断活动",
    goal: "幼儿能判断进餐和生活行为，看到需要调整的做法时说出替代动作。",
    steps: ["听行为", "举绿牌或红牌", "听正确做法", "演一演替代动作"],
    aiCanGenerate: "判断题、正确做法提示、表扬语、家庭复习话术",
  },
  {
    title: "习惯故事小剧场",
    themeId: "habit" as const,
    scene: "餐前餐后、排队过渡、整理后、午睡前短故事",
    goal: "幼儿能说出想听的故事，听完一本短绘本，翻页后完成阅读打卡。",
    steps: ["说想听的故事", "听绘本", "翻到最后一页", "今天读完啦"],
    aiCanGenerate: "原创绘本、封面提示词、阅读后小问题、家园共读话术、表扬语",
  },
  {
    title: "闽食小小播报员",
    themeId: "food" as const,
    scene: "语言区、表演区、班级展示",
    goal: "幼儿能选择一种泉州美食，用名字、食材和发现组成一句小小播报词。",
    steps: ["选一种美食", "听提示卡", "组合介绍句", "上台播报或同伴分享"],
    aiCanGenerate: "播报示范、上台口令、表扬语、家园介绍任务",
  },
  {
    title: "泉州小厨房",
    themeId: "food" as const,
    scene: "生活区、角色区、食育区域活动",
    goal: "幼儿能按顺序点制作动作卡，参与泉州美食角色扮演，理解帮忙和整理。",
    steps: ["选一道美食", "按步骤做动作", "念小厨师口令", "分享完成感受"],
    aiCanGenerate: "小厨师口令、步骤儿歌、区域材料建议、家庭小任务",
  },
  {
    title: "珍惜粮食小列车",
    themeId: "habit" as const,
    scene: "进餐习惯、劳动教育、家园共育",
    goal: "幼儿能理解按需取餐、感谢劳动、餐后整理是珍惜粮食的小行动。",
    steps: ["听粮食旅行故事", "选按需取餐", "感谢劳动", "餐后整理打卡"],
    aiCanGenerate: "粮食旅行故事、进餐口号、感谢语、家庭小管家任务",
  },
  {
    title: "家庭美食小管家",
    themeId: "habit" as const,
    scene: "家园共育、进餐习惯延续、亲子任务",
    goal: "幼儿能在家参与饭前洗手、摆碗筷、尝试一小步和餐后整理。",
    steps: ["饭前洗手", "摆碗筷", "说一种食物发现", "餐后整理一个小地方"],
    aiCanGenerate: "家庭任务卡、亲子提醒语、家园同步建议、温和表扬语",
  },
  {
    title: "睡前故事小回顾",
    themeId: "habit" as const,
    scene: "离园前谈话、睡前亲子共读、家庭延续反馈",
    goal: "幼儿能回顾今天听到的故事或认识的食物，说出一个角色、画面或明天愿意尝试的一小步。",
    steps: ["回想今天故事", "说一个角色或画面", "说一个小发现", "约定明天一小步"],
    aiCanGenerate: "睡前回顾问题、亲子共读任务、家庭反馈话术、鼓励语",
  },
];

export const parentHomeTaskCards = [
  {
    title: "一日常规小接力",
    icon: "✨",
    tasks: ["饭前洗手", "主动喝水", "需要如厕会表达", "等待轮流", "整理玩具图书"],
  },
  {
    title: "习惯故事居家任务",
    icon: "📚",
    tasks: ["亲子共读 5 分钟", "孩子说一个角色", "讲一个画面", "看完书放回原位", "给老师留一句"],
  },
  {
    title: "家庭美食小管家",
    icon: "🏠",
    tasks: ["饭前洗手", "摆碗筷", "文明进餐", "感谢做饭的人", "餐后整理"],
  },
  {
    title: "亲子尝新小挑战",
    icon: "🥢",
    tasks: ["看一看", "闻一闻", "摸一摸", "尝米粒或汤汁", "说一个发现"],
  },
  {
    title: "香菇葱蒜观察卡",
    icon: "🍄",
    tasks: ["找一找香菇", "认一认小葱", "闻一闻蒜味", "不急着吃", "说出名字就打卡"],
  },
  {
    title: "睡前美食/故事小回顾",
    icon: "🌙",
    tasks: ["今天认识了什么", "哪一个味道最熟悉", "哪一种还陌生", "明天想试哪一小步"],
  },
];

export const mealTrayOptions = [
  {
    label: "泉州海蛎煎",
    icon: "🦪",
    nutrient: "蛋白质",
    benefit: "帮助身体长力气。",
    tryTip: "先看金黄边，再尝一小口。",
    isHealthy: true,
  },
  {
    label: "面线糊",
    icon: "🥣",
    nutrient: "主食能量",
    benefit: "让小肚子有暖暖的力气。",
    tryTip: "先用勺子搅一搅，看细面线。",
    isHealthy: true,
  },
  {
    label: "润饼菜",
    icon: "🌯",
    nutrient: "蔬菜和主食",
    benefit: "认识卷起来的蔬菜和饼皮。",
    tryTip: "先找一种认识的蔬菜。",
    isHealthy: true,
  },
  {
    label: "崇武鱼卷",
    icon: "🐟",
    nutrient: "蛋白质",
    benefit: "认识来自海边的鱼肉味。",
    tryTip: "先看圆圆鱼卷，再喝一口汤。",
    isHealthy: true,
  },
  {
    label: "闽南肉粽",
    icon: "🍙",
    nutrient: "主食和家常食材",
    benefit: "认识粽叶、米粒和家乡节日味。",
    tryTip: "先闻粽叶香，再找米粒。",
    isHealthy: true,
  },
  {
    label: "石花膏",
    icon: "🍧",
    nutrient: "清凉甜品",
    benefit: "认识泉州夏天常见的透明甜品。",
    tryTip: "先看透明冻晃一晃。",
    isHealthy: true,
  },
  {
    label: "苹果片",
    icon: "🍎",
    nutrient: "维生素",
    benefit: "给餐盘添一点清甜。",
    tryTip: "咔嚓咬一小口。",
    isHealthy: true,
  },
  {
    label: "汽水",
    icon: "🥤",
    nutrient: "甜饮料",
    benefit: "偶尔认识，不做今天主角。",
    tryTip: "今天先把水和汤放前面。",
    isHealthy: false,
  },
  {
    label: "薯片",
    icon: "🍟",
    nutrient: "油炸零食",
    benefit: "偶尔认识，不做今天主角。",
    tryTip: "今天先多看看闽南食物。",
    isHealthy: false,
  },
];
